'use client';
import { useMemo, useState, useTransition, type FormEvent, type ReactNode } from 'react';
import { useRouter } from 'next/navigation';
import { useI18n } from '@/shared/i18n/I18nProvider';
import { CourtlyAlert } from '@/shared/ui/CourtlyAlert';
import type { Professional, ProfessionalPageData } from '../domain/professional';
import { inviteProfessionalAction, reassignFutureAppointmentsAction, saveProfessionalAccessAction, saveProfessionalAction, saveSpecialtyAction, setProfessionalStatusAction } from '../application/professional-actions';
import { ProfessionalAvatarEditor } from './ProfessionalAvatarEditor';
import styles from './professionals.module.css';

type Modal = 'form'|'details'|'access'|'deactivate'|'specialty'|null;
type RegistrationDraft={authority:string;registrationNumber:string;region:string};
type AvailabilityDraft={weekday:number;enabled:boolean;startTime:string;endTime:string};
const defaultAvailability:AvailabilityDraft[]=Array.from({length:7},(_,weekday)=>({weekday,enabled:weekday>0&&weekday<6,startTime:'08:00',endTime:'18:00'}));
const emptyForm={id:'',firstName:'',lastName:'',preferredName:'',jobTitle:'',email:'',phone:'',birthDate:'',countryCode:'BR',documentType:'',documentNumber:'',notes:'',specialtyIds:[] as string[],activityIds:[] as string[],registrations:[{authority:'',registrationNumber:'',region:''}] as RegistrationDraft[],availabilityRules:defaultAvailability};
const norm=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const digits=(v:string)=>v.replace(/\D/g,'');

export function ProfessionalsClient({initialData}:{initialData:ProfessionalPageData}){
  const {dictionary}=useI18n(); const t=dictionary.professionals; const router=useRouter(); const [pending,startTransition]=useTransition();
  const [modal,setModal]=useState<Modal>(null); const [selected,setSelected]=useState<Professional|null>(null); const [form,setForm]=useState(emptyForm); const [feedback,setFeedback]=useState<{type:'success'|'error';message:string}|null>(null);
  const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [specialty,setSpecialty]=useState(''); const [docType,setDocType]=useState(''); const [docNumber,setDocNumber]=useState(''); const [regAuthority,setRegAuthority]=useState(''); const [regNumber,setRegNumber]=useState(''); const [newSpecialty,setNewSpecialty]=useState('');
  const [replacementId,setReplacementId]=useState(''); const [role,setRole]=useState<'ADMIN'|'PROFESSIONAL'>('PROFESSIONAL'); const [inviteEmail,setInviteEmail]=useState(''); const [permissionOverrides,setPermissionOverrides]=useState<Record<string,boolean>>({});

  const filtered=useMemo(()=>initialData.professionals.filter(p=>{
    const hay=norm([p.fullName,p.preferredName,p.documentNumber,p.registrations.map(r=>`${r.authority} ${r.registrationNumber}`).join(' ')].filter(Boolean).join(' '));
    return (!search||hay.includes(norm(search))) && (!status||(status==='ACTIVE'?p.active:!p.active)) && (!specialty||p.specialties.some(s=>s.id===specialty)) && (!docType||p.documentType===docType) && (!docNumber||digits(p.documentNumber??'').includes(digits(docNumber))) && (!regAuthority||p.registrations.some(r=>r.authority===regAuthority)) && (!regNumber||p.registrations.some(r=>norm(r.registrationNumber).includes(norm(regNumber))));
  }),[initialData.professionals,search,status,specialty,docType,docNumber,regAuthority,regNumber]);

  const openNew=()=>{setSelected(null);setForm(emptyForm);setModal('form');};
  const openEdit=(p:Professional)=>{setSelected(p);setForm({id:p.id,firstName:p.firstName,lastName:p.lastName,preferredName:p.preferredName??'',jobTitle:p.jobTitle??'',email:p.email??'',phone:p.phone??'',birthDate:p.birthDate??'',countryCode:p.countryCode??'BR',documentType:p.documentType??'',documentNumber:p.documentNumber??'',notes:p.notes??'',specialtyIds:p.specialties.map(s=>s.id),activityIds:p.activityIds,registrations:p.registrations.length?p.registrations.map(r=>({authority:r.authority,registrationNumber:r.registrationNumber,region:r.region??''})):[{authority:'',registrationNumber:'',region:''}],availabilityRules:defaultAvailability.map(base=>{const found=p.availabilityRules.find(r=>r.weekday===base.weekday&&r.active);return found?{weekday:base.weekday,enabled:true,startTime:String(found.startTime).slice(0,5),endTime:String(found.endTime).slice(0,5)}:{...base,enabled:false};})});setModal('form');};
  const age=(birth:string|null)=>{if(!birth)return null;const b=new Date(`${birth}T00:00:00`),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a;};
  function submit(e:FormEvent){e.preventDefault();startTransition(async()=>{const result=await saveProfessionalAction(form);if(!result.success){setFeedback({type:'error',message:t.feedback.saveFailed});return;}setModal(null);setFeedback({type:'success',message:t.feedback.saved});router.refresh();});}
  async function confirmDisable(){if(!selected)return;const result=await setProfessionalStatusAction(selected.id,false);if(!result.success){setFeedback({type:'error',message:t.feedback.statusFailed});return;}const future=Number(result.data?.futureAppointments??0);setFeedback({type:'success',message:future?t.feedback.disabledWithAppointments.replace('{count}',String(future)):t.feedback.disabled});setModal(null);router.refresh();}
  const clearFilters=()=>{setSearch('');setStatus('');setSpecialty('');setDocType('');setDocNumber('');setRegAuthority('');setRegNumber('');};
  const allAuthorities=Array.from(new Set(initialData.professionals.flatMap(p=>p.registrations.map(r=>r.authority)))).sort();

  return <main className={styles.page}>
    <header className={styles.header}><div><span>{t.eyebrow}</span><h1>{t.title}</h1><p>{t.description}</p></div>{initialData.canCreate&&<button className={styles.primary} onClick={openNew}>{t.actions.new}</button>}</header>
    {feedback&&<CourtlyAlert type={feedback.type} message={feedback.message}/>} 
    <section className={styles.filters}>
      <label><span>{t.filters.search}</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.filters.searchPlaceholder}/></label>
      <label><span>{t.filters.status}</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t.filters.all}</option><option value="ACTIVE">{t.status.active}</option><option value="INACTIVE">{t.status.inactive}</option></select></label>
      <label><span>{t.filters.specialty}</span><select value={specialty} onChange={e=>setSpecialty(e.target.value)}><option value="">{t.filters.all}</option>{initialData.specialties.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label><span>{t.fields.documentType}</span><select value={docType} onChange={e=>setDocType(e.target.value)}><option value="">{t.filters.all}</option><option>CPF</option><option>PASSPORT</option><option>OTHER</option></select></label>
      <label><span>{t.fields.documentNumber}</span><input value={docNumber} onChange={e=>setDocNumber(e.target.value)}/></label>
      <label><span>{t.filters.registrationAuthority}</span><select value={regAuthority} onChange={e=>setRegAuthority(e.target.value)}><option value="">{t.filters.all}</option>{allAuthorities.map(x=><option key={x}>{x}</option>)}</select></label>
      <label><span>{t.filters.registrationNumber}</span><input value={regNumber} onChange={e=>setRegNumber(e.target.value)}/></label>
      <button className={styles.clear} onClick={clearFilters}>{t.filters.clear}</button>
    </section>
    <div className={styles.summary}><strong>{t.summary.all}: {initialData.professionals.length}</strong><span>{t.summary.active}: {initialData.professionals.filter(x=>x.active).length}</span><span>{t.summary.inactive}: {initialData.professionals.filter(x=>!x.active).length}</span></div>
    <section className={styles.list}>
      <div className={styles.listHead}><span>{t.list.professional}</span><span>{t.list.specialty}</span><span>{t.list.document}</span><span>{t.list.phone}</span><span>{t.list.privilege}</span><span>{t.list.status}</span><span>{t.list.actions}</span></div>
      {filtered.map(p=><article key={p.id} className={styles.row}>
        <div className={styles.identity}>{p.avatarUrl?<img src={p.avatarUrl} alt={p.fullName}/>:<div className={styles.avatar}>{p.fullName.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div>}<button className={styles.linkButton} onClick={()=>{setSelected(p);setModal('details')}}><strong>{p.fullName}</strong><small>{p.jobTitle??t.notProvided}</small></button></div>
        <span>{p.specialties.map(s=>s.name).join(', ')||t.notProvided}</span><span>{p.documentNumber??t.notProvided}</span><span>{p.phone??t.notProvided}</span><span>{p.role??t.access.noAccess}</span><span className={p.active?styles.active:styles.inactive}>{p.active?t.status.active:t.status.inactive}</span>
        <div className={styles.actions}>{initialData.canEdit&&<button onClick={()=>openEdit(p)}>{t.actions.edit}</button>}{initialData.canManageAccess&&<button onClick={()=>{setSelected(p);setRole((p.role==='ADMIN'?'ADMIN':'PROFESSIONAL'));setInviteEmail(p.email??'');setPermissionOverrides(Object.fromEntries(permissionCodes.map(code=>[code,p.permissions.includes(code as any)])));setModal('access')}}>{t.actions.access}</button>}{initialData.canDisable&&(p.active?<button onClick={()=>{setSelected(p);setReplacementId('');setModal('deactivate')}}>{t.actions.disable}</button>:<button onClick={()=>startTransition(async()=>{await setProfessionalStatusAction(p.id,true);router.refresh()})}>{t.actions.enable}</button>)}</div>
      </article>)}
      {!filtered.length&&<p className={styles.empty}>{t.filters.noResults}</p>}
    </section>

    {modal==='form'&&<Dialog title={selected?t.form.editTitle:t.form.newTitle} onClose={()=>setModal(null)}><form className={styles.form} onSubmit={submit}>
      <div className={styles.grid}><Field label={t.fields.firstName}><input required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></Field><Field label={t.fields.lastName}><input required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></Field><Field label={t.fields.preferredName}><input value={form.preferredName} onChange={e=>setForm({...form,preferredName:e.target.value})}/></Field><Field label={t.fields.jobTitle}><input value={form.jobTitle} onChange={e=>setForm({...form,jobTitle:e.target.value})}/></Field><Field label={t.fields.email}><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label={t.fields.phone}><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label={t.fields.country}><input maxLength={2} value={form.countryCode} onChange={e=>setForm({...form,countryCode:e.target.value.toUpperCase()})}/></Field><Field label={t.fields.birthDate}><input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})}/></Field><Field label={t.fields.documentType}><select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})}><option value="">{t.notProvided}</option><option>CPF</option><option>PASSPORT</option><option>OTHER</option></select></Field><Field label={t.fields.documentNumber}><input value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})}/></Field></div>
      <fieldset><legend>{t.fields.specialties}</legend><div className={styles.checks}>{initialData.specialties.filter(s=>s.active).map(s=><label key={s.id}><input type="checkbox" checked={form.specialtyIds.includes(s.id)} onChange={e=>setForm({...form,specialtyIds:e.target.checked?[...form.specialtyIds,s.id]:form.specialtyIds.filter(x=>x!==s.id)})}/>{s.name}</label>)}</div></fieldset>
      <fieldset><legend>{t.fields.services}</legend><div className={styles.checks}>{initialData.activities.filter(a=>a.active).map(a=><label key={a.id}><input type="checkbox" checked={form.activityIds.includes(a.id)} onChange={e=>setForm({...form,activityIds:e.target.checked?[...form.activityIds,a.id]:form.activityIds.filter(x=>x!==a.id)})}/>{a.name}</label>)}</div></fieldset>
      <fieldset><legend>{t.fields.availability}</legend><div className={styles.availabilityList}>{form.availabilityRules.map((r,i)=><div className={styles.availabilityRow} key={r.weekday}><label><input type="checkbox" checked={r.enabled} onChange={e=>{const x=[...form.availabilityRules];x[i]={...x[i],enabled:e.target.checked};setForm({...form,availabilityRules:x})}}/>{t.weekdays[r.weekday]}</label><input type="time" disabled={!r.enabled} value={r.startTime} onChange={e=>{const x=[...form.availabilityRules];x[i]={...x[i],startTime:e.target.value};setForm({...form,availabilityRules:x})}}/><input type="time" disabled={!r.enabled} value={r.endTime} onChange={e=>{const x=[...form.availabilityRules];x[i]={...x[i],endTime:e.target.value};setForm({...form,availabilityRules:x})}}/></div>)}</div></fieldset>
      <fieldset><legend>{t.fields.registrations}</legend>{form.registrations.map((r,i)=><div className={styles.registration} key={i}><input placeholder={t.fields.registrationAuthority} value={r.authority} onChange={e=>{const x=[...form.registrations];x[i]={...x[i],authority:e.target.value};setForm({...form,registrations:x})}}/><input placeholder={t.fields.registrationNumber} value={r.registrationNumber} onChange={e=>{const x=[...form.registrations];x[i]={...x[i],registrationNumber:e.target.value};setForm({...form,registrations:x})}}/><input placeholder={t.fields.registrationRegion} value={r.region} onChange={e=>{const x=[...form.registrations];x[i]={...x[i],region:e.target.value};setForm({...form,registrations:x})}}/></div>)}<button type="button" onClick={()=>setForm({...form,registrations:[...form.registrations,{authority:'',registrationNumber:'',region:''}]})}>{t.actions.addRegistration}</button></fieldset>
      <Field label={t.fields.notes}><textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className={styles.modalActions}><button type="button" onClick={()=>setModal(null)}>{t.actions.cancel}</button><button className={styles.primary} disabled={pending}>{t.actions.save}</button></div></form></Dialog>}

    {modal==='details'&&selected&&<Dialog title={selected.fullName} onClose={()=>setModal(null)}><ProfessionalAvatarEditor professionalId={selected.id} avatarUrl={selected.avatarUrl} fullName={selected.fullName} labels={{change:t.avatar.change,remove:t.avatar.remove,invalid:t.avatar.invalid}}/><div className={styles.details}><p><b>{t.fields.age}:</b> {age(selected.birthDate)??t.notProvided}</p><p><b>{t.fields.country}:</b> {selected.countryCode??t.notProvided}</p><p><b>{t.fields.documentNumber}:</b> {selected.documentNumber??t.notProvided}</p><p><b>{t.fields.specialties}:</b> {selected.specialties.map(x=>x.name).join(', ')||t.notProvided}</p><p><b>{t.fields.registrations}:</b> {selected.registrations.map(x=>`${x.authority} ${x.registrationNumber}${x.region?`-${x.region}`:''}`).join(', ')||t.notProvided}</p><p><b>{t.fields.services}:</b> {initialData.activities.filter(a=>selected.activityIds.includes(a.id)).map(a=>a.name).join(', ')||t.notProvided}</p><p><b>{t.fields.notes}:</b> {selected.notes??t.notProvided}</p></div></Dialog>}

    {modal==='deactivate'&&selected&&<Dialog title={t.deactivate.title} onClose={()=>setModal(null)}><p>{t.deactivate.description.replace('{name}',selected.fullName)}</p><label className={styles.stack}><span>{t.deactivate.replacement}</span><select value={replacementId} onChange={e=>setReplacementId(e.target.value)}><option value="">{t.deactivate.noReplacement}</option>{initialData.professionals.filter(p=>p.active&&p.id!==selected.id).map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select></label><div className={styles.modalActions}><button onClick={()=>setModal(null)}>{t.actions.cancel}</button><button className={styles.danger} onClick={()=>startTransition(async()=>{if(replacementId){const r=await reassignFutureAppointmentsAction(selected.id,replacementId);if(!r.success){setFeedback({type:'error',message:t.feedback.reassignFailed});return;}}await confirmDisable();})}>{t.actions.disable}</button></div></Dialog>}

    {modal==='access'&&selected&&<Dialog title={t.access.title} onClose={()=>setModal(null)}><div className={styles.form}><p>{t.access.description}</p>{!selected.userId&&<><Field label={t.fields.email}><input value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/></Field><Field label={t.access.level}><select value={role} onChange={e=>setRole(e.target.value as any)}><option value="PROFESSIONAL">PROFESSIONAL</option><option value="ADMIN">ADMIN</option></select></Field><button className={styles.primary} disabled={pending||!inviteEmail} onClick={()=>startTransition(async()=>{const r=await inviteProfessionalAction(selected.id,inviteEmail,role);setFeedback({type:r.success?'success':'error',message:r.success?t.feedback.invited:t.feedback.inviteFailed});if(r.success){setModal(null);router.refresh();}})}>{t.access.invite}</button></>}{selected.userId&&<><Field label={t.access.level}><select value={role} onChange={e=>setRole(e.target.value as any)}><option value="PROFESSIONAL">PROFESSIONAL</option><option value="ADMIN">ADMIN</option></select></Field><div className={styles.permissionGrid}>{permissionCodes.map(code=><label key={code}><input type="checkbox" checked={permissionOverrides[code]??false} onChange={e=>setPermissionOverrides({...permissionOverrides,[code]:e.target.checked})}/><span>{code}</span></label>)}</div><button className={styles.primary} onClick={()=>startTransition(async()=>{const r=await saveProfessionalAccessAction({professionalId:selected.id,role,permissionOverrides});setFeedback({type:r.success?'success':'error',message:r.success?t.feedback.accessSaved:t.feedback.accessFailed});if(r.success){setModal(null);router.refresh();}})}>{t.actions.save}</button></>}</div></Dialog>}

    {modal==='specialty'&&<Dialog title={t.specialties.new} onClose={()=>setModal(null)}><Field label={t.fields.specialties}><input value={newSpecialty} onChange={e=>setNewSpecialty(e.target.value)}/></Field><button className={styles.primary} onClick={()=>startTransition(async()=>{const r=await saveSpecialtyAction(newSpecialty);if(r.success){setNewSpecialty('');setModal(null);router.refresh();}})}>{t.actions.save}</button></Dialog>}
    {initialData.canEdit&&<button className={styles.floatingSecondary} onClick={()=>setModal('specialty')}>{t.specialties.manage}</button>}
  </main>;
}

const permissionCodes=['CUSTOMERS_VIEW','CUSTOMERS_CREATE','CUSTOMERS_EDIT','SERVICES_VIEW','SERVICES_CREATE','SERVICES_EDIT','PROFESSIONALS_VIEW','PROFESSIONALS_CREATE','PROFESSIONALS_EDIT','PROFESSIONALS_DISABLE','SCHEDULING_VIEW_ALL','SCHEDULING_VIEW_OWN','SCHEDULING_CREATE','SCHEDULING_EDIT','SCHEDULING_CANCEL','SCHEDULING_RESCHEDULE','ATTENDANCE_VIEW','ATTENDANCE_MANAGE','MAKEUPS_VIEW','MAKEUPS_MANAGE','FINANCIAL_VIEW','FINANCIAL_MANAGE'] as const;
function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className={styles.overlay}><section className={styles.dialog} role="dialog" aria-modal="true"><header><h2>{title}</h2><button onClick={onClose}>×</button></header>{children}</section></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className={styles.stack}><span>{label}</span>{children}</label>}
