'use server';

import { revalidatePath } from 'next/cache';
import { createClient } from '@/shared/database/supabase/server';
import { createAdminClient } from '@/shared/database/supabase/admin';
import { can, getCurrentAccessContext, type PermissionCode } from '@/shared/auth/permissions';

export type ProfessionalActionResult = { success: true; data?: any } | { success: false; error: string };
const clean = (value: unknown) => typeof value === 'string' && value.trim() ? value.trim() : null;

export async function saveProfessionalAction(input: any): Promise<ProfessionalActionResult> {
  try {
    const supabase = await createClient(); const context = await getCurrentAccessContext(supabase); const db = supabase as any;
    const editing = Boolean(input.id); if (!can(context, editing ? 'PROFESSIONALS_EDIT' : 'PROFESSIONALS_CREATE')) return { success: false, error: 'forbidden' };
    const firstName = clean(input.firstName); const lastName = clean(input.lastName); if (!firstName || !lastName) return { success: false, error: 'nameRequired' };
    const payload = { organization_id: context.organizationId, name: `${firstName} ${lastName}`.trim(), first_name: firstName, last_name: lastName, preferred_name: clean(input.preferredName), job_title: clean(input.jobTitle), email: clean(input.email), phone: clean(input.phone), birth_date: clean(input.birthDate), country_code: clean(input.countryCode)?.toUpperCase() ?? null, document_type: clean(input.documentType), document_number: clean(input.documentNumber), notes: clean(input.notes) };
    let id = input.id as string | undefined;
    if (id) { const { error } = await db.from('professionals').update(payload).eq('id', id).eq('organization_id', context.organizationId); if (error) throw error; }
    else { const { data, error } = await db.from('professionals').insert({ ...payload, active: true }).select('id').single(); if (error) throw error; id = data.id; }
    await db.from('professional_specialty_assignments').delete().eq('professional_id', id).eq('organization_id', context.organizationId);
    if (Array.isArray(input.specialtyIds) && input.specialtyIds.length) { const { error } = await db.from('professional_specialty_assignments').insert(input.specialtyIds.map((specialtyId: string) => ({ organization_id: context.organizationId, professional_id: id, specialty_id: specialtyId }))); if (error) throw error; }
    await db.from('professional_activities').delete().eq('professional_id', id).eq('organization_id', context.organizationId);
    if (Array.isArray(input.activityIds) && input.activityIds.length) { const { error } = await db.from('professional_activities').insert(input.activityIds.map((activityId: string) => ({ organization_id: context.organizationId, professional_id: id, activity_id: activityId }))); if (error) throw error; }
    await db.from('professional_registrations').delete().eq('professional_id', id).eq('organization_id', context.organizationId);
    const regs = (input.registrations ?? []).filter((r: any) => clean(r.authority) && clean(r.registrationNumber));
    if (regs.length) { const { error } = await db.from('professional_registrations').insert(regs.map((r: any) => ({ organization_id: context.organizationId, professional_id: id, authority: clean(r.authority), registration_number: clean(r.registrationNumber), region: clean(r.region) }))); if (error) throw error; }
    await db.from('professional_availability_rules').delete().eq('professional_id', id).eq('organization_id', context.organizationId);
    const availability = (input.availabilityRules ?? []).filter((r: any) => r.enabled && r.startTime && r.endTime && r.endTime > r.startTime);
    if (availability.length) { const { error } = await db.from('professional_availability_rules').insert(availability.map((r: any) => ({ organization_id: context.organizationId, professional_id: id, weekday: Number(r.weekday), start_time: r.startTime, end_time: r.endTime, active: true }))); if (error) throw error; }
    revalidatePath('/professionals'); revalidatePath('/scheduling'); return { success: true, data: { id } };
  } catch (e) { console.error('[PROFESSIONALS] save failed', e); return { success: false, error: 'saveFailed' }; }
}

export async function saveSpecialtyAction(name: string): Promise<ProfessionalActionResult> {
  try { const supabase = await createClient(); const context = await getCurrentAccessContext(supabase); if (!can(context, 'PROFESSIONALS_EDIT')) return { success: false, error: 'forbidden' }; const value = clean(name); if (!value) return { success: false, error: 'invalidData' }; const { error } = await (supabase as any).from('professional_specialties').insert({ organization_id: context.organizationId, name: value }); if (error && error.code !== '23505') throw error; revalidatePath('/professionals'); return { success: true }; } catch (e) { console.error(e); return { success: false, error: 'saveFailed' }; }
}

export async function setProfessionalStatusAction(professionalId: string, active: boolean): Promise<ProfessionalActionResult> {
  try { const supabase = await createClient(); const context = await getCurrentAccessContext(supabase); if (!can(context, 'PROFESSIONALS_DISABLE')) return { success: false, error: 'forbidden' }; const { data, error } = await (supabase as any).rpc('set_professional_active_status', { p_professional_id: professionalId, p_active: active }); if (error) throw error; revalidatePath('/professionals'); revalidatePath('/scheduling'); return { success: true, data: { futureAppointments: Number(data?.[0]?.future_appointments ?? 0) } }; } catch (e) { console.error(e); return { success: false, error: 'statusFailed' }; }
}

export async function reassignFutureAppointmentsAction(fromProfessionalId: string, toProfessionalId: string): Promise<ProfessionalActionResult> {
  try { const supabase = await createClient(); const context = await getCurrentAccessContext(supabase); if (!can(context, 'SCHEDULING_RESCHEDULE')) return { success: false, error: 'forbidden' }; const { data, error } = await (supabase as any).rpc('reassign_professional_future_appointments', { p_from_professional_id: fromProfessionalId, p_to_professional_id: toProfessionalId }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; revalidatePath('/professionals'); revalidatePath('/scheduling'); return { success: true, data: { moved: Number(row?.moved ?? 0), remaining: Number(row?.remaining ?? 0) } }; } catch (e) { console.error(e); return { success: false, error: 'reassignFailed' }; }
}

export async function saveProfessionalAccessAction(input: { professionalId: string; role: 'ADMIN' | 'PROFESSIONAL'; permissionOverrides: Record<string, boolean> }): Promise<ProfessionalActionResult> {
  try { const supabase = await createClient(); const context = await getCurrentAccessContext(supabase); if (!can(context, 'PROFESSIONALS_MANAGE_ACCESS')) return { success: false, error: 'forbidden' }; const db = supabase as any; const { data: professional, error: pError } = await db.from('professionals').select('user_id').eq('id', input.professionalId).eq('organization_id', context.organizationId).single(); if (pError || !professional?.user_id) return { success: false, error: 'noAccessAccount' }; const admin = createAdminClient() as any; const { data: membership, error: mError } = await admin.from('memberships').update({ role: input.role }).eq('organization_id', context.organizationId).eq('user_id', professional.user_id).select('id').single(); if (mError) throw mError; await admin.from('membership_permission_overrides').delete().eq('membership_id', membership.id); const rows = Object.entries(input.permissionOverrides).map(([permission_code, allowed]) => ({ membership_id: membership.id, permission_code, allowed })); if (rows.length) { const { error } = await admin.from('membership_permission_overrides').insert(rows); if (error) throw error; } await db.from('audit_logs').insert({ organization_id: context.organizationId, actor_user_id: (await supabase.auth.getUser()).data.user?.id, entity_type: 'PROFESSIONAL', entity_id: input.professionalId, action: 'ACCESS_UPDATED', metadata: { role: input.role } }); revalidatePath('/professionals'); return { success: true }; } catch (e) { console.error(e); return { success: false, error: 'accessFailed' }; }
}

export async function inviteProfessionalAction(professionalId: string, email: string, role: 'ADMIN' | 'PROFESSIONAL'): Promise<ProfessionalActionResult> {
  try { const supabase = await createClient(); const context = await getCurrentAccessContext(supabase); if (!can(context, 'PROFESSIONALS_MANAGE_ACCESS')) return { success: false, error: 'forbidden' }; const db = supabase as any; const { data: professional, error } = await db.from('professionals').select('id,first_name,last_name,user_id').eq('id', professionalId).eq('organization_id', context.organizationId).single(); if (error || !professional) return { success: false, error: 'notFound' }; if (professional.user_id) return { success: false, error: 'alreadyHasAccess' }; const admin = createAdminClient(); const redirectTo = process.env.NEXT_PUBLIC_APP_URL ? `${process.env.NEXT_PUBLIC_APP_URL}/reset-password` : undefined; const invited = await admin.auth.admin.inviteUserByEmail(email, { redirectTo, data: { full_name: `${professional.first_name} ${professional.last_name}`.trim() } }); if (invited.error || !invited.data.user) throw invited.error ?? new Error('invite failed'); const userId = invited.data.user.id; const adminDb = admin as any; const { error: membershipError } = await adminDb.from('memberships').insert({ organization_id: context.organizationId, user_id: userId, role }); if (membershipError) throw membershipError; const { error: updateError } = await adminDb.from('professionals').update({ user_id: userId, email, access_status: 'INVITED' }).eq('id', professionalId); if (updateError) throw updateError; revalidatePath('/professionals'); return { success: true }; } catch (e) { console.error('[PROFESSIONALS] invite failed', e); return { success: false, error: 'inviteFailed' }; }
}

export async function uploadProfessionalAvatarAction(professionalId: string, formData: FormData): Promise<ProfessionalActionResult> {
  try { const supabase = await createClient(); const context = await getCurrentAccessContext(supabase); if (!can(context, 'PROFESSIONALS_EDIT')) return { success: false, error: 'forbidden' }; const file = formData.get('avatar'); if (!(file instanceof File) || file.size === 0) return { success: false, error: 'avatarRequired' }; if (file.size > 5 * 1024 * 1024) return { success: false, error: 'avatarTooLarge' }; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) return { success: false, error: 'invalidAvatarType' }; const ext = file.type === 'image/png' ? 'png' : file.type === 'image/webp' ? 'webp' : 'jpg'; const db = supabase as any; const { data: current } = await db.from('professionals').select('avatar_path').eq('id', professionalId).eq('organization_id', context.organizationId).single(); const path = `professionals/${context.organizationId}/${professionalId}/avatar-${Date.now()}.${ext}`; const { error: up } = await supabase.storage.from('avatars').upload(path, file, { contentType: file.type, upsert: false }); if (up) throw up; const { error: save } = await db.from('professionals').update({ avatar_path: path }).eq('id', professionalId).eq('organization_id', context.organizationId); if (save) { await supabase.storage.from('avatars').remove([path]); throw save; } if (current?.avatar_path) await supabase.storage.from('avatars').remove([current.avatar_path]); revalidatePath('/professionals'); return { success: true }; } catch (e) { console.error(e); return { success: false, error: 'avatarUploadFailed' }; }
}

export async function removeProfessionalAvatarAction(professionalId: string): Promise<ProfessionalActionResult> {
  try { const supabase = await createClient(); const context = await getCurrentAccessContext(supabase); if (!can(context, 'PROFESSIONALS_EDIT')) return { success: false, error: 'forbidden' }; const db = supabase as any; const { data } = await db.from('professionals').select('avatar_path').eq('id', professionalId).eq('organization_id', context.organizationId).single(); if (data?.avatar_path) await supabase.storage.from('avatars').remove([data.avatar_path]); const { error } = await db.from('professionals').update({ avatar_path: null }).eq('id', professionalId); if (error) throw error; revalidatePath('/professionals'); return { success: true }; } catch (e) { console.error(e); return { success: false, error: 'avatarRemoveFailed' }; }
}
